name: Visual testings
on: [push]
jobs:
  Visual_testings:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build storybook
        run: npm run build-storybook

      - name: Run visual tests
        run: npm run test:visual
